namespace StatusBarKind {
    export const level = StatusBarKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    hiro.setImage(assets.image`我的影像`)
    pause(100)
    hiro.setImage(assets.image`hiro`)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    if (controller.A.isPressed()) {
        statusbars.getStatusBarAttachedTo(StatusBarKind.EnemyHealth, sprite).value += parseFloat("-" + 10 * level_1)
        if (statusbars.getStatusBarAttachedTo(StatusBarKind.EnemyHealth, sprite).value == 0) {
            tiles.placeOnRandomTile(sprite, sprites.castle.tileGrass2)
            statusbar2.value += 100 / level_1
            statusbars.getStatusBarAttachedTo(StatusBarKind.EnemyHealth, sprite).value = 100
            _ += 10
        }
    }
})
sprites.onCreated(SpriteKind.Enemy, function (sprite) {
    statusbar3 = statusbars.create(20, 4, StatusBarKind.EnemyHealth)
    statusbar3.attachToSprite(sprite)
    tiles.placeOnRandomTile(sprite, sprites.castle.tileGrass2)
    sprite.follow(hiro, 30)
})
statusbars.onStatusReached(StatusBarKind.Health, statusbars.StatusComparison.LTE, statusbars.ComparisonType.Percentage, 0, function (status) {
    info.setScore(level_1 * 10 + _)
    game.gameOver(true)
})
statusbars.onStatusReached(StatusBarKind.level, statusbars.StatusComparison.GTE, statusbars.ComparisonType.Percentage, 100, function (status) {
    level_1 += 1
    hiro.sayText("level up:LV" + level_1, 500, false)
    statusbar2.value = 0
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.setImage(assets.image`我的影像0`)
    statusbar.value += -4 / level_1
    pause(200)
    otherSprite.setImage(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `)
    pause(200)
})
let my_enemy: Sprite = null
let statusbar3: StatusBarSprite = null
let statusbar2: StatusBarSprite = null
let statusbar: StatusBarSprite = null
let hiro: Sprite = null
let level_1 = 0
let _ = 0
_ = 0
let 位置 = 1
level_1 = 1
tiles.setCurrentTilemap(tilemap`層級1`)
let textSprite2 = textsprite.create("LV" + level_1, 0, 2)
textSprite2.setPosition(10, 20)
hiro = sprites.create(assets.image`hiro`, SpriteKind.Player)
controller.moveSprite(hiro, 100, 100)
scene.cameraFollowSprite(hiro)
statusbar = statusbars.create(20, 5, StatusBarKind.Health)
statusbar.setColor(8, 2)
statusbar.attachToSprite(hiro, 0, -5)
statusbar2 = statusbars.create(50, 5, StatusBarKind.level)
statusbar2.value = 0
statusbar2.setColor(5, 1)
statusbar2.setPosition(27, 5)
let textSprite3 = textsprite.create(convertToText(_), 0, 15)
textSprite3.setPosition(60, 5)
let textSprite = textsprite.create("新手草原", 0, 2)
textSprite.scale = 2
textSprite.setPosition(75, 55)
pause(1000)
sprites.destroy(textSprite)
forever(function () {
    textSprite3.setText(convertToText(_))
    textSprite3.setFlag(SpriteFlag.RelativeToCamera, true)
})
forever(function () {
    if (位置 == 1) {
        my_enemy = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        pause(20000)
    }
})
forever(function () {
    textSprite2.setText("LV" + level_1)
    textSprite2.setFlag(SpriteFlag.RelativeToCamera, true)
})
forever(function () {
    if (level_1 == 20) {
        位置 += 1
        tiles.setCurrentTilemap(tilemap`層級3`)
        textSprite = textsprite.create("幽暗森林", 0, 2)
        pause(1000)
        sprites.destroy(textSprite)
    }
})
forever(function () {
    if (位置 == 1) {
        my_enemy = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        pause(20000)
    }
})
forever(function () {
    if (statusbar.value < 100 && controller.B.isPressed()) {
        statusbar.value += level_1
        pause(500)
    }
})
